# Generated by Django 4.2.2 on 2023-06-28 06:12

from django.db import migrations
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', teacher.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
