# Generated by Django 4.2.2 on 2023-06-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='classs', to='school.school'),
        ),
    ]
